Smalltalk createPackage: 'Microengine-Adapters'!
Object subclass: #MEAdapter
	slots: {}
	package: 'Microengine-Adapters'!

MEAdapter subclass: #MEAudioAdapter
	slots: {}
	package: 'Microengine-Adapters'!

MEAudioAdapter subclass: #MEMusicAdapter
	slots: {}
	package: 'Microengine-Adapters'!

MEAudioAdapter subclass: #MESoundAdapter
	slots: {}
	package: 'Microengine-Adapters'!

MEAdapter subclass: #MEGameAdapter
	slots: {}
	package: 'Microengine-Adapters'!

