Smalltalk createPackage: 'Microengine-Node'!
Object subclass: #MEBoundingVolume
	slots: {}
	package: 'Microengine-Node'!

MEBoundingVolume subclass: #MEBoxBound
	slots: {}
	package: 'Microengine-Node'!

MEBoundingVolume subclass: #MEPolygonBound
	slots: {}
	package: 'Microengine-Node'!

MEBoundingVolume subclass: #MESphereBound
	slots: {}
	package: 'Microengine-Node'!

Object subclass: #MENode
	slots: {#currentLocation. #bounds}
	package: 'Microengine-Node'!

MENode subclass: #MEAudioNode
	slots: {}
	package: 'Microengine-Node'!

MENode subclass: #MEElementNode
	slots: {}
	package: 'Microengine-Node'!

MEElementNode subclass: #MEPlayer
	slots: {}
	package: 'Microengine-Node'!

MENode subclass: #MEGraphicNode
	slots: {}
	package: 'Microengine-Node'!

MEGraphicNode subclass: #MECamera
	slots: {}
	package: 'Microengine-Node'!

MEGraphicNode subclass: #MESpriteNode
	slots: {}
	package: 'Microengine-Node'!

MEGraphicNode subclass: #METextNode
	slots: {}
	package: 'Microengine-Node'!

MENode subclass: #MEPhysicsNode
	slots: {}
	package: 'Microengine-Node'!

Object subclass: #MEProperty
	slots: {}
	package: 'Microengine-Node'!

MEProperty subclass: #MELife
	slots: {}
	package: 'Microengine-Node'!

MEProperty subclass: #MEScore
	slots: {}
	package: 'Microengine-Node'!

MEProperty subclass: #MEVelocity
	slots: {}
	package: 'Microengine-Node'!

